### ISSUE TITLE
crash on inject

### ISSUE THREAD

**Issue by ataranIen** [NMan1/Overflow-CSGO#1]
crashes on inject / menu opening

**Comment by NMan1** [comment]
Never happened to me before. Are you compiling on x86? Attach visual studios debugger and see where it crashes

**Comment by NMan1** [comment]
Actually its probably because you dont have the right fonts installed.
If you want the direct download to it:
https://anonymousfiles.io/wnR51NK4/

Its also been updated in the repo if you would rather download it there.
