### ISSUE TITLE
Skin Changer -disable_d3d9ex 

### ISSUE THREAD

**Issue by AhamYT** [NMan1/Overflow-CSGO#12]
I had this problem a while ago. A possible reason the skins become black is when you search for "models/player" in dme or se. then overriding the material to null causes to black skins. try changing it from checking models/player to something like is player render chams. 

Quick note. Change your dme code from matrix3x4_t to matrix_t. so you can properly setup bones.

**Comment by NMan1** [comment]
Thank you! I’ll try that, it is quite annoying to have to always use that launch flag.

**Comment by AhamYT** [comment]
Can you add me on discord? Aham#2650

**Comment by NMan1** [comment]
My discord is in my bio if you want to contact me.
